HaikuArchives/Pe

- Resources/Dialog-Preferences.r
I have made the spelling of the word "colour" consistent.
This addresses issue #4, and is for the following Google Code-in task: https://codein.withgoogle.com/dashboard/task-instances/5797000020754432/
> Make spelling consistent

- Resources/Bindings.r
Because all the keys has raw_char = B_FUNCTION_KEY are triggered to display document in Web+
Users should delete "keybindings-v2" file under your Pe settings (~/config/settings/pe) to generate the keymap again.
Fixes https://dev.haiku-os.org/ticket/12857
> Unbind B_FUNCTION_KEY from "Help"

- Languages/Sources/HtmlCssJsPhp_Popup.cpp
A std::map cannot have 3 parameters. Additionally, the variable created (headings) was never used so the line was unnecessary.
> Removed line 461 as it was causing a compile error.

- Languages/Sources/Rez_Language.cpp
This is a rather quick and dirty fix. Since rez's syntax is close to identical to rdef's, it doesn't hurt to have rdef files highlighted using rez's syntax highlighter.
> Syntax Highlighting for RDEF Files

- Extensions/HeaderHeader.cpp
This makes sure it matches the text from Haiku's Coding Guidelines.
> HeaderHeader: added the missing "All rights reserved" part.

- Extensions/HeaderHeader.cpp
- Extensions/JRandom.cpp
- Extensions/Pipe.cpp
Fixes the following warnings:
- HeaderHeader.cpp: -Wliteral-suffix.
- JRandom.cpp: -Wregister.
- Pipe.cpp: -Wcatch-value and -Wformat-overflow.
> Extensions: fix warnings.

- Languages/Sources/Diff_Language.cpp
This comes in handy for Haikuporter's .patchset files, as each individual commit "Subject" gets used as a separator in the function popup.
> Diff_Language: add detection of "Subject" lines on patchset files.

- Sources/PApp.cpp
It was opening an empty Web+ due to it not handling the Net+ way of doing things.
> Fix opening of help docs files with Web+ (or other default browser)

- Sources/PApp.cpp
The existing code fails to show the docs, if the browser is already running for some reason. It's also unnecessarily complicated. Just having be_roster launch the preferred app for text/html with the URL in the message is simpler.
If the browser is already running, it pops to the front when loading the doc anyway.
> Fix showing Help doc

- Languages/Sources/Lout_Popup.l
That's what's used in the Haikuports' version of Lout.
Also:
- only AddInclude() if the path exists.
- restore a "path.Append(subDir)" call that got lost in a change
in 2013.
- minor tweaks.
Could use some further clean up using BStrings more extensibly,
but for now, this will do.
> Lout_Popup: use B_FIND_PATH_DATA_DIRECTORY to find Lout's data

- Sources/PDoc.cpp
This was preventing, for example, Lout's languge addon use of the "open includes" feature, as it was computing absolute paths that Pe's code didn't seemed to handle (at least when the files where not on the same dir as the doc being edited).
> Make PDoc::OpenInclude() support absolute paths.

- Jamrules
This allows building Pe with either GCC2, or GCC13 (the latter after a simple call to `setarch x86`).
Should also help building it with HaikuPorter, if we decide to move Pe to "x86" arch.
---
Change tested on beta4, 32 bits (both `setarch x86_gcc2` and `setarch x86_gcc2`), and 64 bits too.
> Fix detection of GCC13 on x86 32 bits.

- Sources/PText.cpp
> Save/Restore "Show invisibles" setting.

- Sources/CKeyCapturer.cpp
Adding, for example, an "OPT+P" shortcut, will work regardless of the state of num-lock, so adding it to the shortcut description just causes confusion.
> Avoid adding "Numlock-" in DescribeKeys().

- Resources/Bindings.r
- Sources/PExec.h
- Sources/PMessages.h
- Sources/PText.cpp
- Sources/PText.h
Added a new "Execute command and send output to Worksheet" command. Default keybinding is CMD+Shift+ENTER.
On existing Pe installations, you need to manually assign a keybinding for the new command, under:
Preferences->Keybindings->Miscellaneous
> Partial/alternative solution to #64.

- Sources/CDiffWindow.cpp
- Sources/PApp.cpp
- Sources/PMessages.h
When called as `Pe --diff file1 file2`, it automatically opens the "File differences" dialog for both files, ready to be used.
First attempt at adding this functionality. Suggestions always welcomed!
Ideally, `lpe` should also be able to call this mode. Haven't looked at that yet.
> Allow invoking the "Find differences" mode from the command line.

- Sources/CDiffWindow.cpp
- Sources/PApp.cpp
1.- Fix tiny "Differences", window if files are an exact match.
I think that, ideally, no windows should open if files are identical, and the "diff mode" was invoked from the command line / lpe.
But that can be a future improvement.
2.- Make sure the "Differences" window is the active one, and the that the focus is on the list of differences.
> "diff mode" improvements.

- Resources/Dialog-Preferences.r
- Sources/CMenuItem.cpp
- Sources/PDoc.cpp
- Sources/Utils.cpp
- Sources/pe.h
Pretty low-effort (3 AM, currently here :-P) attempt to address #71.
Opening as draft, as "Add file", "Remove file", and "Project->Group" menu items do not work as intended with current Paladin (see notes on the linked issue above).
> Replace BeIDE with Paladin if compiling on Haiku.

- Sources/PApp.cpp
- lpe/lpe.cpp
> Support opening files with `file:line:col` style arguments.

- .gitignore
- Jamrules
- build/BuildSettings
This allows building, for example, for both 32 and 64 bits on x86 from a single repo clone,  right out of the box.
Kind of a silly workaround, but unless Jam provides something better than $OSPLAT... this will have to do.
> Use separate "generated" dirs per arch.

- Extensions/Jamfile
Commit b8f4143c60b428ab91c1322c8d5594352cc6f515 changed UI strings to use "Haiku's sentence casing", but that change broke the "Replace As Tabs" extension (as it changed a non-user visible string in ConvertTabs.cpp that should have been kept in sync with the actual name of the extension's binary).
Fix by just using sentence casing for the extensions' binary names (those are the ones used in the menu).
Changed a couple other names' casing just for consistency.
> Extensions: fix "Replace as tabs" by fixing the case in extensions names.

- Sources/CFindDialog.cpp
Pressing CTRL+down_arrow on a Find dialog, with no previous search patterns registered, was causing an "Exception (Segment violation)".
> Avoid crash on Find dialog.
